# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

apt_packages:
 - r-cran-ggplot2
 - r-cran-terra
 - r-cran-rasterVis

## Email notification if the package pass status changes
notifications:
  email:
    recipients:
      - robboy@ceh.ac.uk
    on_success: change
    on_failure: change

# Warnings dont fail build
warnings_are_errors: false
